import {he, wi} from '../first/responsive.js'
export {tl_phone, tl, tl_0, tl_1, tl_2, tl_phone_0, tl_phone_1, tl_phone_2}

let tl = gsap.timeline({paused: true});
tl.set("#menu-laptop-blur-opened", {visibility: "visible", height:document.body.offsetHeight}).add('start')
.to("#menu-text", {duration:0.2, delay:0, opacity:0, ease:Power2.easeInOut})
.set("#menu-text", {duration:0.2, delay:0, display:'none', ease:Power2.easeInOut})
.to("#ham-menu", {duration:0.4, delay:0, height:30, width:26, ease:Power2.easeInOut}, 'start')
.to("#ham2", {duration:0.2, delay:0, width:0, ease: Power1.easeOut}, 'start')
.to("#ham1", {duration:0.4, delay:0, rotate: 45, width:26, ease:Power2.easeInOut}, 'start')
.to("#ham3", {duration:0.4, delay:0, rotate: -45, width:26, y:4, ease:Power2.easeInOut}, 'start')
.to("#menu-laptop", {duration: 0.5, delay:0, right: 0, ease: Power1.easeOut})
.to("#menu-laptop-blur-opened", {duration:1, delay:-1, opacity:0.3, ease: Power2.easeInOut})
.fromTo("#menu-laptop-line-top", {width:0}, {width:0.33*wi, duration:0.7, ease:Power2.easeOut, delay:0.75}, 'start')
.fromTo("#menu-laptop-line-right", {height:0}, {height:he, duration:0.7, ease:Power2.easeOut, delay:0.75}, 'start')
.fromTo('#menu-laptop-etablissement-text', {opacity:0, x:10}, {opacity:1, x:0, duration:0.9, ease:Power2.easeOut, delay:0.8}, 'start')
.fromTo('#menu-laptop-lycee-text', {opacity:0, x:10}, {opacity:1, x:0, duration:0.9, ease:Power2.easeOut, delay:-0.8})
.fromTo('#menu-laptop-college-text', {opacity:0, x:10}, {opacity:1, x:0, duration:0.9, ease:Power2.easeOut, delay:-0.8})
.fromTo('#menu-laptop-primaire', {opacity:0, x:10}, {opacity:1, x:0, duration:0.9, ease:Power2.easeOut, delay:-0.8})
.fromTo('#menu-laptop-ecole-directe', {opacity:0, x:10}, {opacity:1, x:0, duration:0.9, ease:Power2.easeOut, delay:-0.8})

let tl_phone = gsap.timeline({paused: true});
tl_phone.add('start')
.add("start_menu")
.to("#menu-text", {duration:0.4, delay:0, opacity:0, ease:Power2.easeInOut}, "start")
.set("#menu-text", {duration:0.4, delay:0, display:'none', ease:Power2.easeInOut}, "start")
.to("#ham2", {duration:0.4, delay:0, width:0, ease: Power1.easeOut}, 'start')
.to("#ham1", {duration:0.4, delay:0, rotate: 45, width:26, ease:Power2.easeInOut}, 'start')
.to("#ham3", {duration:0.4, delay:0, rotate: -45, width:26, ease:Power2.easeInOut}, 'start')
.to("#phone_menu_background", {duration: 1, delay: 0, width: (he>wi)? 2.5*he : 2.5*wi, height: (he>wi)? 2.5*he : 2.5*wi, ease:Power2.easeInOut}, 'start')
.to(".main_thema", {opacity: 1, x: -20, duration: 0.3, stagger: 0.2})

let tl_phone_0 = gsap.timeline({paused: true})
tl_phone_0.add("start")
.set("#thema_1_child", {display: "block"})
.to("#thema_1_child", {height: 90})
.to("#option_1_child_thema_1", {opacity: 1, duration: 0.4, x: -20, delay: -0.4})
.to("#option_2_child_thema_1", {opacity: 1, duration: 0.4, x: -20, delay: -0.2})
.to("#option_3_child_thema_1", {opacity: 1, duration: 0.4, x: -20, delay: -0.2})


let tl_phone_1 = gsap.timeline({paused: true})
tl_phone_1.add("start")
.set("#thema_2_child", {display: "block"})
.to("#thema_2_child", {height: 90})
.to("#option_1_child_thema_2", {opacity: 1, duration: 0.4, x: -20, delay: -0.2})
.to("#option_2_child_thema_2", {opacity: 1, duration: 0.4, x: -20, delay: -0.2})
.to("#option_3_child_thema_2", {opacity: 1, duration: 0.4, x: -20, delay: -0.2})

let tl_phone_2 = gsap.timeline({paused: true})
tl_phone_2.add("start")
.set("#thema_3_child", {display: "block"})
.to("#thema_3_child", {height: 60})
.to("#option_1_child_thema_3", {opacity: 1, duration: 0.4, x: -20, delay: -0.2})
.to("#option_2_child_thema_3", {opacity: 1, duration: 0.4, x: -20, delay: -0.2})

let tl_0 = gsap.timeline({paused:true})
tl_0.set("#menu-laptop-etablissement-options", {display: "flex"})
.add("start")
.to("#menu-laptop-fleche0", {rotate:180, duration:0.5, ease:Power2.easeInOut}, "start")
.to("#menu-laptop-etablissement-options", {height:100, duration:0.3, ease:Power2.easeInOut}, "start")
.to("#menu-laptop-etablissement-option0", {opacity:1, y:0, duration:0.45, delay:0.1, ease:Power2.easeOut}, "start")
.to("#menu-laptop-etablissement-option1", {opacity:1, y:0, duration:0.45, delay:-0.3, ease:Power2.easeOut})
.to("#menu-laptop-etablissement-option2", {opacity:1, y:0, duration:0.45, delay:-0.3, ease:Power2.easeOut})

let tl_1 = gsap.timeline({paused:true})
tl_1.set("#menu-laptop-lycee-options", {display: "flex"})
.add("start")
.to("#menu-laptop-fleche1", {rotate:180, duration:0.5, ease:Power2.easeInOut}, "start")
.to("#menu-laptop-lycee-options", {height:100, duration:0.3, ease:Power2.easeInOut}, "start")
.to("#menu-laptop-lycee-option0", {opacity:1, y:0, duration:0.45, delay:0.1, ease:Power2.easeOut}, "start")
.to("#menu-laptop-lycee-option1", {opacity:1, y:0, duration:0.45, delay:-0.3, ease:Power2.easeOut})
.to("#menu-laptop-lycee-option2", {opacity:1, y:0, duration:0.45, delay:-0.3, ease:Power2.easeOut})

let tl_2 = gsap.timeline({paused:true})
tl_2.set("#menu-laptop-college-options", {display: "flex"})
.add("start")
.to("#menu-laptop-fleche2", {rotate:180, duration:0.5, ease:Power2.easeInOut}, "start")
.to("#menu-laptop-college-options", {height:70, duration:0.3, ease:Power2.easeInOut}, "start")
.to("#menu-laptop-college-option0", {opacity:1, y:0, duration:0.45, delay:0.1, ease:Power2.easeOut}, "start")
.to("#menu-laptop-college-option1", {opacity:1, y:0, duration:0.45, delay:-0.3, ease:Power2.easeOut})
